sam_business_inherit:
    resource: "@CanalTPSamCoreBundle/Resources/config/routing.yml"

canal_tp_sam_homepage:
    path:  /
    defaults: { _controller: CanalTPSamCoreBundle:Sam:index }

sam_customer_list:
    path:  /customer
    defaults: { _controller: CanalTPNmmPortalBundle:Customer:list }

sam_customer_new:
    path:  /customer/new
    defaults: { _controller: CanalTPNmmPortalBundle:Customer:new }

sam_customer_edit:
    path:  /customer/{id}/edit
    defaults: { _controller: CanalTPNmmPortalBundle:Customer:edit }

sam_customer_show:
    path:  /customer/{id}/show
    defaults: { _controller: CanalTPNmmPortalBundle:Customer:show }

canal_tp_sam_network_list_json:
    path: /coverage/{externalCoverageId}/networks
    defaults: { _controller: CanalTPSamCoreBundle:Customer:byCoverage }
    options:
        expose: true

#canal_tp_sam_network_check_permission_json:
#    path: /coverage/{externalCoverageId}/networks/{externalNetworkId}/{token}
#    defaults: { _controller: CanalTPSamCoreBundle:Customer:checkAllowedToNetwork }
#    requirements:
#        token: -?[a-zA-Z0-9_\-:]*
#    options:
#        expose: true

sam_customer_regeneratetoken:
    path:  /customer/{id}/token/{appId}/regenerate
    defaults: { _controller: CanalTPNmmPortalBundle:Customer:regenerateToken }

sam_customer_regeneratealltokens:
    path:  /customer/{id}/tokens/regenerate
    defaults: { _controller: CanalTPNmmPortalBundle:Customer:regenerateTokens }

sam_customer_listtokens:
    path:  /customer/{id}/tokens
    defaults: { _controller: CanalTPNmmPortalBundle:Customer:listTokens }
